if(NOT DEFINED ELIO_DEFINITIONS_FILE OR NOT EXISTS "${ELIO_DEFINITIONS_FILE}")
    message(FATAL_ERROR "Generated HTTP/2 test definitions are required")
endif()

file(STRINGS "${ELIO_DEFINITIONS_FILE}" _definitions)
set(_expected elio_tests)
if(ELIO_SANITIZER_SUITES)
    list(APPEND _expected elio_tests_asan elio_tests_tsan)
endif()
foreach(_target IN LISTS _expected)
    set(_found FALSE)
    foreach(_line IN LISTS _definitions)
        if(_line MATCHES "^${_target}:" AND _line MATCHES "(^|[:;])ELIO_HAS_HTTP2=1(;|$)")
            set(_found TRUE)
        endif()
    endforeach()
    if(NOT _found)
        message(FATAL_ERROR "${_target} does not compile HTTP/2-specific test coverage")
    endif()
endforeach()
