file(READ "${ROOT}/README.md" readme)
file(READ "${ROOT}/examples/first_coroutine.cpp" example)
string(FIND "${readme}" "### Your First Coroutine" heading)
if(heading LESS 0)
    message(FATAL_ERROR "README first-coroutine section is missing")
endif()
string(SUBSTRING "${readme}" ${heading} -1 section)
string(FIND "${section}" "```cpp\n" opening)
if(opening LESS 0)
    message(FATAL_ERROR "README first-coroutine code fence is missing")
endif()
math(EXPR opening "${opening} + 7")
string(SUBSTRING "${section}" ${opening} -1 section)
string(FIND "${section}" "```" closing)
if(closing LESS 0)
    message(FATAL_ERROR "README first-coroutine code fence is unclosed")
endif()
string(SUBSTRING "${section}" 0 ${closing} snippet)
string(STRIP "${snippet}" snippet)
string(STRIP "${example}" example)
if(NOT snippet STREQUAL example)
    message(FATAL_ERROR "README first-coroutine snippet differs from the compiled example")
endif()
execute_process(COMMAND "${EXAMPLE}" RESULT_VARIABLE result
    OUTPUT_VARIABLE output ERROR_VARIABLE errors TIMEOUT 20)
string(STRIP "${output}" stripped_output)
if(NOT result STREQUAL "0" OR NOT stripped_output STREQUAL "Result: 42")
    message(FATAL_ERROR "First coroutine did not complete successfully: ${result}\n${output}\n${errors}")
endif()
