if(EXISTS "/home/ray.dr/Git/Elio/build_warn/tests/elio_tests_tsan-b12d07c_tests.cmake")
  include("/home/ray.dr/Git/Elio/build_warn/tests/elio_tests_tsan-b12d07c_tests.cmake")
else()
  add_test(elio_tests_tsan_NOT_BUILT-b12d07c elio_tests_tsan_NOT_BUILT-b12d07c)
endif()
