# CMake generated Testfile for 
# Source directory: /home/runner/work/Elio/Elio/tests
# Build directory: /home/runner/work/Elio/Elio/build-rereview/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
include("/home/runner/work/Elio/Elio/build-rereview/tests/elio_tests-b12d07c_include.cmake")
include("/home/runner/work/Elio/Elio/build-rereview/tests/elio_tests_asan-b12d07c_include.cmake")
include("/home/runner/work/Elio/Elio/build-rereview/tests/elio_tests_tsan-b12d07c_include.cmake")
include("/home/runner/work/Elio/Elio/build-rereview/tests/elio_rdma_cuda_lifetime_tests-b12d07c_include.cmake")
include("/home/runner/work/Elio/Elio/build-rereview/tests/elio_rdma_ibverbs_backend_stub_tests-b12d07c_include.cmake")
add_test([=[elio_fork_boundary]=] "/home/runner/work/Elio/Elio/build-rereview/tests/elio_fork_boundary_tests")
set_tests_properties([=[elio_fork_boundary]=] PROPERTIES  RUN_SERIAL "TRUE" TIMEOUT "60" _BACKTRACE_TRIPLES "/home/runner/work/Elio/Elio/tests/CMakeLists.txt;243;add_test;/home/runner/work/Elio/Elio/tests/CMakeLists.txt;0;")
add_test([=[elio_fork_boundary_asan]=] "/home/runner/work/Elio/Elio/build-rereview/tests/elio_fork_boundary_tests_asan")
set_tests_properties([=[elio_fork_boundary_asan]=] PROPERTIES  RUN_SERIAL "TRUE" TIMEOUT "60" _BACKTRACE_TRIPLES "/home/runner/work/Elio/Elio/tests/CMakeLists.txt;246;add_test;/home/runner/work/Elio/Elio/tests/CMakeLists.txt;0;")
add_test([=[package_rdma_cuda_export_metadata]=] "/usr/local/bin/cmake" "-DELIO_SOURCE_DIR=/home/runner/work/Elio/Elio" "-DELIO_BINARY_DIR=/home/runner/work/Elio/Elio/build-rereview/tests/cmake/package_rdma_cuda_export" "-P" "/home/runner/work/Elio/Elio/tests/cmake/check_rdma_cuda_package_export.cmake")
set_tests_properties([=[package_rdma_cuda_export_metadata]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/Elio/Elio/tests/CMakeLists.txt;275;add_test;/home/runner/work/Elio/Elio/tests/CMakeLists.txt;0;")
add_test([=[rdma_cuda_example_api_metadata]=] "/usr/local/bin/cmake" "-DELIO_SOURCE_DIR=/home/runner/work/Elio/Elio" "-P" "/home/runner/work/Elio/Elio/tests/cmake/check_rdma_cuda_example_api.cmake")
set_tests_properties([=[rdma_cuda_example_api_metadata]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/Elio/Elio/tests/CMakeLists.txt;282;add_test;/home/runner/work/Elio/Elio/tests/CMakeLists.txt;0;")
add_test([=[package_liburing_export_metadata]=] "/usr/local/bin/cmake" "-DELIO_SOURCE_DIR=/home/runner/work/Elio/Elio" "-DELIO_BINARY_DIR=/home/runner/work/Elio/Elio/build-rereview/tests/cmake/package_liburing_export" "-P" "/home/runner/work/Elio/Elio/tests/cmake/check_liburing_package_export.cmake")
set_tests_properties([=[package_liburing_export_metadata]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/Elio/Elio/tests/CMakeLists.txt;288;add_test;/home/runner/work/Elio/Elio/tests/CMakeLists.txt;0;")
add_test([=[package_threads_export_metadata]=] "/usr/local/bin/cmake" "-DELIO_SOURCE_DIR=/home/runner/work/Elio/Elio" "-DELIO_BINARY_DIR=/home/runner/work/Elio/Elio/build-rereview/tests/cmake/package_threads_export" "-P" "/home/runner/work/Elio/Elio/tests/cmake/check_threads_package_export.cmake")
set_tests_properties([=[package_threads_export_metadata]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/Elio/Elio/tests/CMakeLists.txt;295;add_test;/home/runner/work/Elio/Elio/tests/CMakeLists.txt;0;")
add_test([=[package_rdma_dependency_export_metadata]=] "/usr/local/bin/cmake" "-DELIO_SOURCE_DIR=/home/runner/work/Elio/Elio" "-DELIO_BINARY_DIR=/home/runner/work/Elio/Elio/build-rereview/tests/cmake/package_rdma_dependency_export" "-P" "/home/runner/work/Elio/Elio/tests/cmake/check_rdma_dependency_package_export.cmake")
set_tests_properties([=[package_rdma_dependency_export_metadata]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/Elio/Elio/tests/CMakeLists.txt;302;add_test;/home/runner/work/Elio/Elio/tests/CMakeLists.txt;0;")
add_test([=[package_elio_compile_feature_export]=] "/usr/local/bin/cmake" "-DELIO_SOURCE_DIR=/home/runner/work/Elio/Elio" "-DELIO_BINARY_DIR=/home/runner/work/Elio/Elio/build-rereview/tests/cmake/package_elio_compile_feature_export" "-DELIO_PARENT_BINARY_DIR=/home/runner/work/Elio/Elio/build-rereview" "-P" "/home/runner/work/Elio/Elio/tests/cmake/check_elio_compile_feature_export.cmake")
set_tests_properties([=[package_elio_compile_feature_export]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/Elio/Elio/tests/CMakeLists.txt;309;add_test;/home/runner/work/Elio/Elio/tests/CMakeLists.txt;0;")
add_test([=[package_version_compatibility]=] "/usr/local/bin/cmake" "-DELIO_VERSION_FILE=/home/runner/work/Elio/Elio/build-rereview/ElioConfigVersion.cmake" "-P" "/home/runner/work/Elio/Elio/tests/cmake/check_elio_version_compatibility.cmake")
set_tests_properties([=[package_version_compatibility]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/Elio/Elio/tests/CMakeLists.txt;329;add_test;/home/runner/work/Elio/Elio/tests/CMakeLists.txt;0;")
add_test([=[http2_option_requires_http]=] "/usr/local/bin/cmake" "-DELIO_SOURCE_DIR=/home/runner/work/Elio/Elio" "-DELIO_BINARY_DIR=/home/runner/work/Elio/Elio/build-rereview/tests/cmake/http2_option_requires_http" "-P" "/home/runner/work/Elio/Elio/tests/cmake/check_http2_option_dependencies.cmake")
set_tests_properties([=[http2_option_requires_http]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/Elio/Elio/tests/CMakeLists.txt;335;add_test;/home/runner/work/Elio/Elio/tests/CMakeLists.txt;0;")
add_test([=[non_linux_platform_rejected]=] "/usr/local/bin/cmake" "-DELIO_SOURCE_DIR=/home/runner/work/Elio/Elio" "-DELIO_BINARY_DIR=/home/runner/work/Elio/Elio/build-rereview/tests/cmake/non_linux_platform" "-DELIO_FMT_SOURCE_DIR=/home/runner/work/Elio/Elio/build-rereview/_deps/fmt-src" "-DELIO_CMAKE_GENERATOR=Unix Makefiles" "-DELIO_CMAKE_MAKE_PROGRAM=/usr/bin/gmake" "-DELIO_CXX_COMPILER=/usr/bin/c++" "-P" "/home/runner/work/Elio/Elio/tests/cmake/check_linux_platform.cmake")
set_tests_properties([=[non_linux_platform_rejected]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/Elio/Elio/tests/CMakeLists.txt;342;add_test;/home/runner/work/Elio/Elio/tests/CMakeLists.txt;0;")
add_test([=[debugger_script_helpers]=] "/usr/bin/python3.12" "/home/runner/work/Elio/Elio/tests/unit/test_debugger_scripts.py")
set_tests_properties([=[debugger_script_helpers]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/Elio/Elio/tests/CMakeLists.txt;355;add_test;/home/runner/work/Elio/Elio/tests/CMakeLists.txt;0;")
add_test([=[capture_test_evidence_helper]=] "/usr/bin/python3.12" "/home/runner/work/Elio/Elio/tests/unit/test_capture_test_evidence.py")
set_tests_properties([=[capture_test_evidence_helper]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/Elio/Elio/tests/CMakeLists.txt;359;add_test;/home/runner/work/Elio/Elio/tests/CMakeLists.txt;0;")
add_test([=[tcp_benchmark_conformance_summary]=] "/usr/bin/python3.12" "/home/runner/work/Elio/Elio/tests/unit/test_tcp_benchmark_conformance_summary.py")
set_tests_properties([=[tcp_benchmark_conformance_summary]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/Elio/Elio/tests/CMakeLists.txt;363;add_test;/home/runner/work/Elio/Elio/tests/CMakeLists.txt;0;")
