if(EXISTS "/home/runner/work/Elio/Elio/build-rereview/tests/elio_rdma_cuda_lifetime_tests-b12d07c_tests.cmake")
  include("/home/runner/work/Elio/Elio/build-rereview/tests/elio_rdma_cuda_lifetime_tests-b12d07c_tests.cmake")
else()
  add_test(elio_rdma_cuda_lifetime_tests_NOT_BUILT-b12d07c elio_rdma_cuda_lifetime_tests_NOT_BUILT-b12d07c)
endif()
